(() => {
  const options = {'zelda-echoes':'Zelda: Echoes of Wisdom','mario-kart-world':'Mario Kart World',kirby:'Kirby et le monde oublié','donkey-kong':'Donkey Kong Bananza'};
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || 'null') || fallback; } catch (error) { return fallback; } };
  const poll = read('gaming-co-poll-v1', {counts:{'zelda-echoes':0,'mario-kart-world':0,kirby:0,'donkey-kong':0},choice:''});
  Object.keys(options).forEach(key => { poll.counts[key] = Math.max(0, Math.floor(Number(poll.counts[key]) || 0)); });
  const pollForm=document.querySelector('#poll-form'), results=document.querySelector('#poll-results'), feedback=document.querySelector('#poll-feedback');
  function showResults(){
    if(!results)return; const total=Object.keys(options).reduce((sum,key)=>sum+poll.counts[key],0); results.replaceChildren();
    const heading=document.createElement('h3'); heading.textContent='Résultats sur cet appareil'; results.append(heading);
    Object.keys(options).forEach(key=>{const n=poll.counts[key],p=total?Math.round(n/total*100):0,row=document.createElement('div');row.className='poll-result-row';const label=document.createElement('div');label.className='poll-result-label';const name=document.createElement('b');name.textContent=options[key];const amount=document.createElement('span');amount.textContent=n+' vote'+(n>1?'s':'')+' · '+p+'%';label.append(name,amount);const track=document.createElement('div');track.className='poll-result-track';track.setAttribute('role','progressbar');track.setAttribute('aria-label','Votes pour '+options[key]);track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax',String(Math.max(total,1)));track.setAttribute('aria-valuenow',String(n));const fill=document.createElement('span');fill.style.width=p+'%';track.append(fill);row.append(label,track);results.append(row);}); results.hidden=false;
  }
  if(pollForm){if(options[poll.choice]){const input=pollForm.querySelector('input[value="'+poll.choice+'"]');if(input)input.checked=true;showResults();}pollForm.addEventListener('submit',event=>{event.preventDefault();const input=pollForm.querySelector('input[name="game-poll"]:checked');if(!input||!options[input.value]){if(feedback)feedback.textContent='Choisis un jeu avant de voter.';return;}if(poll.choice!==input.value){if(options[poll.choice])poll.counts[poll.choice]=Math.max(0,poll.counts[poll.choice]-1);poll.counts[input.value]++;poll.choice=input.value;}let saved=true;try{localStorage.setItem('gaming-co-poll-v1',JSON.stringify(poll));}catch(error){saved=false;}showResults();if(feedback)feedback.textContent=saved?'Ton vote est gardé sur cet appareil. Tu peux le modifier quand tu veux.':'Le navigateur ne permet pas de garder ce vote après fermeture.';});}
  const form=document.querySelector('#idea-form'),list=document.querySelector('#saved-ideas'),counter=document.querySelector('#idea-count'),ideaFeedback=document.querySelector('#idea-feedback');
  let ideas=read('gaming-co-ideas-v1',[]);if(!Array.isArray(ideas))ideas=[];ideas=ideas.filter(item=>item&&typeof item.title==='string'&&typeof item.details==='string'&&typeof item.type==='string').slice(0,10);
  function saveIdeas(){try{localStorage.setItem('gaming-co-ideas-v1',JSON.stringify(ideas));return true;}catch(error){return false;}}
  function renderIdeas(){if(!list||!counter)return;list.replaceChildren();counter.textContent=ideas.length+' / 10';if(!ideas.length){const empty=document.createElement('p');empty.className='ideas-empty';empty.textContent='Tes idées enregistrées apparaîtront ici.';list.append(empty);return;}ideas.forEach(idea=>{const card=document.createElement('article');card.className='saved-idea';const top=document.createElement('div');top.className='saved-idea-heading';const type=document.createElement('small');type.textContent=idea.type;const remove=document.createElement('button');remove.type='button';remove.className='remove-idea';remove.dataset.removeIdea=idea.id;remove.textContent='Supprimer';remove.setAttribute('aria-label','Supprimer l’idée : '+idea.title);top.append(type,remove);const title=document.createElement('h4');title.textContent=idea.title;const details=document.createElement('p');details.textContent=idea.details;card.append(top,title,details);list.append(card);});}
  if(form){renderIdeas();form.addEventListener('submit',event=>{event.preventDefault();if(ideas.length>=10){if(ideaFeedback)ideaFeedback.textContent='Ton carnet est plein : supprime une idée avant d’en ajouter une autre.';return;}const data=new FormData(form),idea={id:String(Date.now())+'-'+Math.random().toString(36).slice(2,8),type:String(data.get('type')||''),title:String(data.get('title')||'').trim(),details:String(data.get('details')||'').trim()};if(!idea.title||!idea.details)return;ideas.unshift(idea);if(!saveIdeas()){ideas.shift();if(ideaFeedback)ideaFeedback.textContent='Le navigateur ne permet pas de garder cette idée.';return;}renderIdeas();form.reset();if(ideaFeedback)ideaFeedback.textContent='Ton idée a été ajoutée à ton carnet sur cet appareil.';});list.addEventListener('click',event=>{const button=event.target.closest('[data-remove-idea]');if(!button)return;ideas=ideas.filter(idea=>idea.id!==button.dataset.removeIdea);saveIdeas();renderIdeas();if(ideaFeedback)ideaFeedback.textContent='Idée supprimée de ce navigateur.';});}
})();
