const extraGames = [
  { id: 'zelda-totk', name: 'Zelda: Tears of the Kingdom', genre: 'Aventure', description: 'Explore Hyrule, résous des énigmes et invente des machines.', symbol: '△', art: 'zelda', mode: 'Exploration et énigmes', details: ['Link part explorer Hyrule, ses îles dans le ciel et des lieux souterrains. Tu peux suivre l’histoire ou découvrir un chemin, un sanctuaire ou un village aperçu au loin.', 'Les pouvoirs de Link permettent de déplacer et d’assembler des objets pour fabriquer des véhicules et des outils. Il n’y a pas une seule solution aux énigmes : essaie une idée et modifie ta construction si besoin.', 'C’est une aventure qui récompense la curiosité et la créativité. Pense à sauvegarder régulièrement et à faire une pause quand tu le souhaites.'] },
  { id: 'mario-kart-8', name: 'Mario Kart 8 Deluxe', genre: 'Sport', description: 'Fais la course sur des circuits hauts en couleur.', symbol: '🏁', art: 'mariokart', mode: 'Course et compétition', details: ['Choisis un personnage, prépare ton kart et tente de franchir la ligne d’arrivée avant les autres. Les circuits réservent des virages, des raccourcis et des surprises.', 'Tu peux jouer seul, avec des amis sur le même écran ou découvrir plusieurs modes de course et de bataille. Une option de conduite assistée peut aider les débutants à rester sur la piste.', 'Essaie différents circuits, garde un objet pour le bon moment et amuse-toi même si le classement change à la dernière seconde.'] },
  { id: 'super-mario-wonder', name: 'Super Mario Bros. Wonder', genre: 'Aventure', description: 'Traverse des niveaux surprenants et découvre les fleurs prodiges.', symbol: '✿', art: 'mariowonder', mode: 'Plateforme et découverte', details: ['Mario et ses amis parcourent le Royaume des Fleurs dans une aventure de plateforme pleine de couleurs. Chaque niveau propose des obstacles, des pièces et des chemins à explorer.', 'Les fleurs prodiges transforment parfois le niveau : les tuyaux bougent, les personnages se mettent à chanter ou le décor change de forme.', 'Essaie différents badges pour découvrir de nouvelles capacités. En multijoueur local, chacun peut rejoindre la partie et s’entraider.'] },
  { id: 'splatoon-3', name: 'Splatoon 3', genre: 'Action', description: 'Couvre le terrain d’encre et joue en équipe.', symbol: '◉', art: 'splatoon', mode: 'Action et équipe', details: ['Les équipes utilisent des armes à encre pour colorer le terrain et atteindre leurs objectifs. En Guerre de territoire, l’équipe qui a recouvert le plus de surface remporte la partie.', 'Sous sa couleur, ton personnage peut nager rapidement et recharger son encre. Choisis une arme qui te convient et aide ton équipe à couvrir les zones.', 'Le jeu propose aussi une campagne solo et des modes coopératifs. Pour les parties en ligne, vérifie les réglages de communication avec un parent.'] },
  { id: 'pokemon-ecarlate', name: 'Pokémon Écarlate', genre: 'Aventure', description: 'Parcours une grande région et rencontre des Pokémon.', symbol: '◇', art: 'pokemon', mode: 'Aventure et collection', details: ['Pars explorer la région de Paldea, rencontre des Pokémon et complète ton équipe. Tu peux visiter des villes et choisir plusieurs objectifs d’aventure.', 'Les combats se jouent au tour par tour : observe les types de Pokémon et choisis une capacité adaptée. Tu peux collectionner de nouvelles créatures et les entraîner.', 'Prends le temps de découvrir les paysages et les personnages. Les échanges en ligne sont facultatifs ; ne communique pas tes informations personnelles à des inconnus.'] },
  { id: 'among-us', name: 'Among Us', genre: 'Tactique', description: 'Observe les indices et coopère pour terminer les missions.', symbol: '◉', art: 'amongus', mode: 'Déduction et coopération', details: ['L’équipage doit accomplir des missions pendant qu’un imposteur tente de ralentir l’équipe. Observez les indices et décidez ensemble de la suite.', 'Les parties sont courtes et les rôles changent. Tu peux jouer en partie privée avec des personnes que tu connais et régler les options de discussion.', 'Garde les échanges respectueux et quitte une partie si tu ne te sens pas à l’aise.'] },
  { id: 'gta-vi', name: 'Grand Theft Auto VI', genre: 'Action', description: 'Un jeu en monde ouvert : vérifie son âge conseillé avec un parent.', symbol: 'VI', art: 'gta', mode: 'Fiche à voir avec un parent', details: ['GTA VI est un jeu d’action en monde ouvert. Cette fiche présente le jeu, sans recommander d’y jouer.', 'La série GTA comporte des thèmes adultes. À 13 ans, demande à ton parent de vérifier la classification PEGI officielle du jeu avant de décider s’il te convient.', 'Avant de lancer un jeu, regarde toujours son âge conseillé sur la boîte ou la page officielle.'] }
];

games.push(...extraGames);
renderGames();
